# Generated by Django 4.1.1 on 2022-10-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('firstName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('male', models.CharField(max_length=20, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Люди',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
